openapi: "3.0.3"
info:
  title: "backend API"
  description: "backend API"
  version: "1.0.0"
servers:
  - url: "https://backend"
paths:
  /:
    get:
      description: ""
  /import:
    get:
      description: ""
      responses:
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                type: "object"
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "object"
  /routes:
    get:
      description: ""
      parameters:
        - name: "type"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "route"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AllRoutesResponse"
  /routes/{id}:
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "id must be an integer"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FullRoute"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
  /markers:
    get:
      description: ""
      parameters:
        - name: "type"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "route"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "Connection"
          in: "header"
          required: true
          description: "Websocket Connection parameter"
          schema:
            type: "string"
        - name: "Upgrade"
          in: "header"
          required: true
          description: "Websocket Upgrade parameter"
          schema:
            type: "string"
        - name: "Sec-WebSocket-Key"
          in: "header"
          required: true
          description: "Websocket Sec-WebSocket-Key parameter"
          schema:
            type: "string"
      responses:
        "101":
          description: "Switching Protocols"
          headers:
            Connection:
              required: true
              schema:
                type: "string"
            Upgrade:
              required: true
              schema:
                type: "string"
            Sec-WebSocket-Accept:
              required: true
              schema:
                type: "string"
  /markers/json:
    get:
      description: ""
      parameters:
        - name: "type"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "route"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "Connection"
          in: "header"
          required: true
          description: "Websocket Connection parameter"
          schema:
            type: "string"
        - name: "Upgrade"
          in: "header"
          required: true
          description: "Websocket Upgrade parameter"
          schema:
            type: "string"
        - name: "Sec-WebSocket-Key"
          in: "header"
          required: true
          description: "Websocket Sec-WebSocket-Key parameter"
          schema:
            type: "string"
      responses:
        "101":
          description: "Switching Protocols"
          headers:
            Connection:
              required: true
              schema:
                type: "string"
            Upgrade:
              required: true
              schema:
                type: "string"
            Sec-WebSocket-Accept:
              required: true
              schema:
                type: "string"
components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        login:
          type: "string"
        name:
          type: "string"
    Token:
      type: "object"
      properties:
        token:
          type: "string"
        type:
          type: "string"
    AuthResponse:
      type: "object"
      properties:
        user:
          $ref: "#/components/schemas/User"
        token:
          $ref: "#/components/schemas/Token"
    AllRoutesResponse:
      type: "object"
      properties: { }
    LatLng:
      type: "object"
      properties:
        lat:
          type: "number"
          format: "double"
        lng:
          type: "number"
          format: "double"
    Stop:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        latLng:
          $ref: "#/components/schemas/LatLng"
        len:
          type: "integer"
          format: "int32"
    Route:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        route:
          type: "string"
        name:
          type: "string"
        transportType:
          type: "string"
          enum:
            - "value"
            - "BUS"
            - "TROLLEY_BUS"
            - "TRAM"
            - "Minibus"
        firstStop:
          $ref: "#/components/schemas/Stop"
        lastStop:
          $ref: "#/components/schemas/Stop"
    Trace:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        latLng:
          $ref: "#/components/schemas/LatLng"
        stop:
          $ref: "#/components/schemas/Stop"
    FullRoute:
      type: "object"
      properties:
        route:
          $ref: "#/components/schemas/Route"
        traces:
          type: "array"
          items:
            $ref: "#/components/schemas/Trace"